=== marygarzonr/KISKIS/kiskisCode/src/main/resources/dtd/kiskis-0.24.dtd
<!--
    DTD for Keep It Secret! Keep It Safe! from Tobias Buchloh
    $Id: kiskis-0.21.dtd,v 1.1 2007/03/11 22:14:15 tbuchloh Exp $
-->

<!ELEMENT Password EMPTY >
<!ATTLIST Password created CDATA #REQUIRED
			       expires CDATA #REQUIRED
                   pwd CDATA #REQUIRED >

<!ELEMENT Attachment EMPTY >
<!ATTLIST Attachment id CDATA #REQUIRED
			         key CDATA #REQUIRED
                     description CDATA #REQUIRED 
                     uuid CDATA #REQUIRED>

<!ELEMENT PasswordHistory ( Password* ) >

<!ELEMENT Comment ( #PCDATA ) >

<!ELEMENT SecuredElement ( Comment, ( Password, PasswordHistory, Attachment* ) ) >
<!ATTLIST SecuredElement creationDate CDATA #REQUIRED
                         expiresNever ( false | true ) #REQUIRED
                         lastChangeDate CDATA #REQUIRED
                         lastViewedDate CDATA #REQUIRED
                         viewCounter CDATA #REQUIRED
                         name CDATA #REQUIRED
                         archivedOnDate CDATA #IMPLIED
                         uuid CDATA #REQUIRED >

<!ELEMENT BankAccount
				(( SecuredElement, TANList* )
                 | ( TANList*, SecuredElement )) >
<!ATTLIST BankAccount bank CDATA #REQUIRED
                      bankID CDATA #REQUIRED
                      number CDATA #REQUIRED
                      telebankingPin CDATA #REQUIRED >

<!ELEMENT CreditCard ( SecuredElement ) >
<!ATTLIST CreditCard deployer CDATA #REQUIRED
                     number CDATA #REQUIRED
                     pin CDATA #REQUIRED 
                     cardValidationCode CDATA #REQUIRED >

<!ELEMENT Group (Comment, ( BankAccount | CreditCard | GenericAccount | Group | NetAccount | SecuredFile )* ) >
<!ATTLIST Group name CDATA #REQUIRED 
                     archivedOnDate CDATA #IMPLIED
					 uuid CDATA #REQUIRED>

<!ELEMENT NetAccount ( SecuredElement ) >
<!ATTLIST NetAccount email CDATA #REQUIRED
                     url CDATA #REQUIRED
                     username CDATA #REQUIRED >

<!ELEMENT SecuredFile ( SecuredElement ) >
<!ATTLIST SecuredFile file CDATA #REQUIRED >

<!ELEMENT TAN EMPTY >
<!ATTLIST TAN id CDATA #REQUIRED
			  number CDATA #REQUIRED
              used CDATA #IMPLIED >

<!ELEMENT TANList ( TAN* ) >
<!ATTLIST TANList created CDATA #REQUIRED
                  id CDATA #REQUIRED >

<!ELEMENT TPMDocument ( AccountType*, Group ) >
<!ATTLIST TPMDocument version CDATA #REQUIRED 
				  uuid CDATA #REQUIRED >

<!ELEMENT GenericAccount ( AccountPropertyValue*, SecuredElement ) >
<!ATTLIST GenericAccount type CDATA #REQUIRED >

<!ELEMENT AccountType ( AccountProperty* ) >
<!ATTLIST AccountType name CDATA #REQUIRED >

<!ELEMENT AccountProperty EMPTY >
<!ATTLIST AccountProperty name CDATA #REQUIRED
                          type CDATA #REQUIRED >

<!ELEMENT AccountPropertyValue EMPTY >
<!ATTLIST AccountPropertyValue name CDATA #REQUIRED
							   type CDATA #REQUIRED
                               value CDATA #REQUIRED >

=== marygarzonr/KISKIS/kiskisCode/target/classes/tests/kiskis-0.24-w-attachments.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TPMDocument SYSTEM "kiskis-0.24.dtd">
<TPMDocument uuid="1ddc4605-e929-40db-85aa-56180e412f08"
	version="0.24">
	<AccountType name="Komplexes Vorlagenbeispiel">
		<AccountProperty name="Eine Zeichenkette" type="String" />
		<AccountProperty name="Ein Passwort" type="Password" />
		<AccountProperty name="Ein Datum" type="Date" />
		<AccountProperty name="Eine Internet-Adresse" type="URL" />
		<AccountProperty name="Etwas mehr Text" type="Text" />
	</AccountType>
	<AccountType name="Nur Passwort" />
	<Group uuid="b3b40c78-26ee-4d85-a73c-f011f171842f" name="Meine Passwörter">
		<Comment>Kommentar mit
Zeilenumbrüchen,
1
2
3
</Comment>
		<Group uuid="156478f7-f6bc-4d2d-ba10-209c6ed7d6eb" name="Arbeit">
			<Comment>Speichern Sie hier alles, was mit ihrer Arbeit zu tun hat.</Comment>
			<NetAccount email="t.buchloh@gmx.net" username="tobias"
				url="">
				<SecuredElement uuid="90c367d7-eb3d-431a-af9e-9f7761a19f60"
					name="Konto 1" creationDate="2010-10-27T19:35:18" lastChangeDate="2010-10-27T19:38:38"
					expiresNever="true" lastViewedDate="2010-10-27T19:35:23"
					viewCounter="1">
					<Comment />
					<Password pwd="ofAtoT82" expires="2011-10-27" created="2010-10-27T19:38:38" />
					<PasswordHistory>
						<Password pwd="goGi9120" expires="2011-10-27" created="2010-10-27T19:35:37" />
					</PasswordHistory>
					<Attachment id="1" uuid="04dacafe-c5b5-4cc2-829b-67164403b14a"
						key="a2Fn_Z&gt;yENCh" description="CHANGELOG" />
					<Attachment id="2" uuid="08439fd5-92c1-4285-95c8-e3674c711089"
						key="K}gY&quot;6CaGV+y" description="AUTHORS" />
				</SecuredElement>
			</NetAccount>
		</Group>
		<Group uuid="02bb9f1c-1460-464a-a40c-45627941646e" name="Banken &amp; Finanzen">
			<Comment>Hier können sie ihre Kreditkarten, Bankkonten, etc. ablegen.</Comment>
		</Group>
		<Group uuid="86cdf0fc-3a7a-4038-97bf-e1a0f974c3af" name="Computer, Kommunikation &amp; E-Mail">
			<Comment>Legen Sie hier alles ab, was mit E-Mail, Telefon und
				Computerzugängen zu tun hat.</Comment>
		</Group>
		<Group uuid="263bd570-a5db-443a-ac36-bedeae995f9c" name="Einkaufen">
			<Comment>Hier können Sie ihre Amazon-, eBay- oder bücher.de-Zugänge
				ablegen.</Comment>
			<NetAccount email="test@test.de" username="test" url="">
				<SecuredElement uuid="e6e93f2a-ffa5-4deb-b6fe-50d8b0be7f1c"
					name="Konto 3" creationDate="2010-10-27T19:39:23" lastChangeDate="2010-10-27T19:39:59"
					expiresNever="true" lastViewedDate="2010-10-27T19:39:28"
					viewCounter="1">
					<Comment />
					<Password pwd="faVa0749" expires="2011-10-27" created="2010-10-27T19:39:59" />
					<PasswordHistory />
					<Attachment id="4" uuid="321d0aa6-655d-4a71-8344-bd4713b6e8cd"
						key="oJKbB+I.%w3?" description="README" />
					<Attachment id="5" uuid="b188c1ee-262a-45c6-9187-999a4fb86e28"
						key="%\`VoZT+6Ewp" description="LICENSE" />
					<Attachment id="6" uuid="a3c86196-793e-4724-a109-df3bb363f97f"
						key="J@@0{g97Ks:u" description="build.xml" />
				</SecuredElement>
			</NetAccount>
		</Group>
		<Group uuid="88636557-e891-43ca-9d41-7b6e713ab510" name="Freizeit &amp; Hobbys">
			<Comment>Hier können Sie alles ablegen was mit ihrer Freizeit und
				ihren Hobbies zu tun hat.</Comment>
		</Group>
		<Group uuid="2afc9fbf-f78a-4e70-9e25-cbab43631176" name="Portale">
			<Comment>Hier können Sie ihre netvibes-, iGoogle-, ...-Konten
				ablegen.</Comment>
			<NetAccount email="foo@bar.de" username="gandalf" url="">
				<SecuredElement uuid="bcb0db4f-1f17-4c51-aec0-014299c7efd2"
					name="Konto 2" creationDate="2010-10-27T19:38:43" lastChangeDate="2010-10-27T19:39:13"
					expiresNever="true" lastViewedDate="2010-10-27T19:38:48"
					viewCounter="1">
					<Comment />
					<Password pwd="qANaBE27" expires="2011-10-27" created="2010-10-27T19:39:13" />
					<PasswordHistory />
					<Attachment id="3" uuid="fd4fedae-c341-479b-8bc1-ad22a142baa1"
						key="B=_$D?z7vq4N" description="LICENSE" />
				</SecuredElement>
			</NetAccount>
		</Group>
		<Group uuid="d2e14f3d-a83d-40ac-9723-15a4f5cdb052" name="Sonstige">
			<Comment>Packen Sie hier alles rein, von dem Sie nicht wissen wo es
				sonst hin soll.</Comment>
		</Group>
		<Group uuid="407d4634-261c-4f4f-8330-f5e5a7799641" name="Soziale Netzwerke">
			<Comment>Hier können Sie ihre Facebook-, Xing- oder Twitter-Zugänge
				ablegen.</Comment>
		</Group>
	</Group>
</TPMDocument>
